import "./globals.css";
import { Inter_Tight } from "next/font/google";
import { Button } from "./componenets/Button";

const interTight = Inter_Tight({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-lightGray py-8">
      <body
        className={`${interTight.className} antialiased flex flex-col gap-10  `}
      >
        <div className="w-full container px-10 mx-auto">
          <nav className=" w-full items-center shadow-small justify-between rounded-full px-4 py-2 ps-10 bg-white  flex">
            <div>
              <img src="/images/Logo.png" alt="logo" className="size-10" />
            </div>
            <ul className="flex font-bold items-center text-sm justify-between gap-10">
              <li>Flips</li>
              <li>Properties</li>
              <li>FAQS</li>
              <li>
                <Button size="lg" className="rounded-full h-12 font-bold">
                  White Paper
                </Button>
              </li>
            </ul>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
